name: Renovate

on:
  workflow_dispatch:

  schedule:
    # At minute 0 past hour 8, 14, and 20 on every day-of-week from Monday through Friday.
    - cron: '0 8,14,20 * * 1-5'

jobs:
  renovate:
    name: Run self-hosted Renovate
    runs-on:  ubuntu-latest
    if: >-
      ${{ contains(fromJson('["workflow_dispatch", "schedule"]'), github.event_name) ||
          github.event.label.name == 'renovate-rebase' }}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0

      - name: Check SHA in GH Actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@0168d43369f2c6661245b8b94a8c812e0867af4b # v2.1.1

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@3cae5833b4ae40ae8e4b9921c5c1a32adeda490b # v34.152.4
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}