name: Renovate

on:
  workflow_dispatch:

  schedule:
    # At minute 0 past hour 8, 14, and 20 on every day-of-week from Monday through Friday.
    - cron: '0 8,14,20 * * 1-5'

jobs:
  renovate:
    name: Run self-hosted Renovate
    runs-on:  ubuntu-latest
    if: >-
      ${{ contains(fromJson('["workflow_dispatch", "schedule"]'), github.event_name) ||
          github.event.label.name == 'renovate-rebase' }}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 0

      - name: Check SHA in GH Actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@21991cec25093947ff3f62e4c223df0260c39944 # v2.1.2

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@2529763aa12e6d5b445bc911e8bd8cce2a4f205c # v36.0.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          useSlim: false
